spring:
  application:
    name: spring-ai

  ai:
    mistralai:
      api-key: ${MISTRAL_AI_API_KEY}
      chat:
        options:
          model: mistral-medium
          max-tokens: 50
          temperature: 0.5
    retry:
      max-attempts: 1
