spring:
  application:
    name: spring-ai

  ai:
    mistralai:
      api-key: ${MISTRAL_AI_API_KEY}
      chat:
        options:
          model: mistral-large-2402
          temperature: 1


logging:
  level:
    org:
      springframework:
        ai:
          converter:
            BeanOutputConverter: DEBUG
    com:
      practice:
        parser:
          controller:
            ParserController: DEBUG